### ISSUE TITLE
Dress

### ISSUE THREAD

**Issue by lukefrasera** [Fratkins/wedding_plan_init#1]
Formal wedding dress or graduation dress.

**Comment by lukefrasera** [comment]
I was thinking about something like this:
![image](https://user-images.githubusercontent.com/2898112/45924781-14b06100-bebd-11e8-8cd4-2623e0f6ee64.png)

There are 3 tasks left:
- [ ] find graduation dress
- [ ] find shoes to math
- [ ] decide on formal dress.

**Comment by tamzinatkins** [comment]
found ceremony dress, thinking i'll wear graduation dress to dinner
